### ISSUE TITLE
Image URL Validation

### ISSUE THREAD

**Issue by rmacklin** [AppFolioOnboarding/image-sharer-conproctor#4]
#### As a user I want to be prevented from submitting invalid image URLs.

Acceptance criteria:
- [x] I cannot successfully save an image with an invalid URL.
- [x] An error message is associated with the appropriate input field on
  failure.

Discussion Topic:
- [x] What is a valid image URL?

Dependencies:
- Save Image Link

**Comment by bboe** [comment]
I reopened this after making a few comments to the PR. When you get a chance could you address those few things and then we can close it up. Overall things are looking great. Thanks!
